# Generated by Django 5.0.7 on 2024-07-29 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_photography_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='photography',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
