# Generated by Django 5.0.7 on 2024-08-05 23:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0006_photography_user_alter_photography_photo_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='photo_date',
            field=models.DateTimeField(
                default=datetime.datetime(2024, 8, 5, 20, 36, 26, 610780)
            ),
        ),
        migrations.AlterField(
            model_name='photography',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
