# Generated by Django 5.0.7 on 2024-08-05 23:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0007_alter_photography_photo_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photography',
            name='photo_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
